# Generated by Django 3.2.6 on 2021-08-26 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyUser',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.abstractmodel')),
                ('full_name', models.CharField(max_length=255)),
            ],
            bases=('app.abstractmodel',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.abstractmodel')),
                ('complete_name', models.CharField(max_length=255)),
            ],
            bases=('app.abstractmodel',),
        ),
    ]
